config/routes.rb
First::Application.routes.draw do
  resources :leitos

  resources :hospitais

  resources :municipios

  resources :gerencias

  resources :macros

end

app/models/municipio.rb
class Municipio < ActiveRecord::Base
  belongs_to :macro
  belongs_to :gerencia

  has_many :municipios
end

app/controllers/municipios_controller.rb
class MunicipiosController < ApplicationController
  # GET /municipios
  # GET /municipios.json
  def index
	@search = Municipio.search(params[:search])
	@municipios = @search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @municipios }
    end
  end

  # GET /municipios/1
  # GET /municipios/1.json
  def show
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @municipio }
    end
  end

  # GET /municipios/new
  # GET /municipios/new.json
  def new
    @municipio = Municipio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @municipio }
    end
  end

  # GET /municipios/1/edit
  def edit
    @municipio = Municipio.find(params[:id])
  end

  # POST /municipios
  # POST /municipios.json
  def create
    @municipio = Municipio.new(params[:municipio])

    respond_to do |format|
      if @municipio.save
        format.html { redirect_to @municipio, notice: 'Municipio was successfully created.' }
        format.json { render json: @municipio, status: :created, location: @municipio }
      else
        format.html { render action: "new" }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /municipios/1
  # PUT /municipios/1.json
  def update
    @municipio = Municipio.find(params[:id])

    respond_to do |format|
      if @municipio.update_attributes(params[:municipio])
        format.html { redirect_to @municipio, notice: 'Municipio was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @municipio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipios/1
  # DELETE /municipios/1.json
  def destroy
    @municipio = Municipio.find(params[:id])
    @municipio.destroy

    respond_to do |format|
      format.html { redirect_to municipios_url }
      format.json { head :ok }
    end
  end
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/views/municipios/_form.html.erb
<%= form_for(@municipio) do |f| %>
  <% if @municipio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@municipio.errors.count, "error") %> prohibited this municipio from being saved:</h2>

      <ul>
      <% @municipio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :macro %><br />
    <%= f.collection_select(:macro_id, Macro.all, :id, :codigo, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :gerencia %><br />
    <%= f.collection_select(:gerencia_id, Gerencia.all, :id, :codigo, :prompt => true) %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cod_geo %><br />
    <%= f.text_field :cod_geo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/municipios/edit.html.erb
<h1>Editing municipio</h1>

<%= render 'form' %>

<%= link_to 'Show', @municipio %> |
<%= link_to 'Back', municipios_path %>

app/views/municipios/index.html.erb
<h1>Listing municipios</h1>

<%= form_for @search, :url => municipios_path, :html => {:method => :get} do |f| %>
  <%= f.label :nome %>
  <%= f.text_field :nome_contains %><br />
  <%= f.label :macro %>
  <%= f.text_field :macro_codigo_contains %><br />
  <%= f.label :grs %>
  <%= f.text_field :gerencia_codigo_contains %><br />
  <%= f.submit 'Localizar'%>
<% end %>

<table>
  <tr>
    <th>Macro</th>
    <th>GRS</th>
    <th>Nome</th>
    <th>Cod geo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @municipios.each do |municipio| %>
  <tr>
    <td><%= municipio.macro.codigo %></td>
    <td><%= municipio.gerencia.codigo %></td>
    <td><%= municipio.nome %></td>
    <td><%= municipio.cod_geo %></td>
    <td><%= link_to 'Show', municipio %></td>
    <td><%= link_to 'Edit', edit_municipio_path(municipio) %></td>
    <td><%= link_to 'Destroy', municipio, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Municipio', new_municipio_path %>

app/views/municipios/new.html.erb
<h1>New municipio</h1>

<%= render 'form' %>

<%= link_to 'Back', municipios_path %>

app/views/municipios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Macro:</b>
  <%= @municipio.macro.codigo %>
</p>

<p>
  <b>Gerencia:</b>
  <%= @municipio.gerencia.codigo %>
</p>

<p>
  <b>Nome:</b>
  <%= @municipio.nome %>
</p>

<p>
  <b>Cod geo:</b>
  <%= @municipio.cod_geo %>
</p>


<%= link_to 'Edit', edit_municipio_path(@municipio) %> |
<%= link_to 'Back', municipios_path %>