config/routes.rb
First::Application.routes.draw do
  resources :leitos

  resources :hospitais

  resources :municipios

  resources :gerencias

  resources :macros

end

app/models/leito.rb
class Leito < ActiveRecord::Base
  belongs_to :hospital
end

app/controllers/leitos_controller.rb
class LeitosController < ApplicationController
  # GET /leitos
  # GET /leitos.json
  def index
    @leitos = Leito.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leitos }
    end
  end

  # GET /leitos/1
  # GET /leitos/1.json
  def show
    @leito = Leito.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leito }
    end
  end

  # GET /leitos/new
  # GET /leitos/new.json
  def new
    @leito = Leito.new

    if params[:hospital]
      @leito.hospital = Hospital.find(params[:hospital])
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leito }
    end
  end

  # GET /leitos/1/edit
  def edit
    @leito = Leito.find(params[:id])
  end

  # POST /leitos
  # POST /leitos.json
  def create
    @leito = Leito.new(params[:leito])

    respond_to do |format|
      if @leito.save
        format.html { redirect_to @leito, notice: 'Leito was successfully created.' }
        format.json { render json: @leito, status: :created, location: @leito }
      else
        format.html { render action: "new" }
        format.json { render json: @leito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leitos/1
  # PUT /leitos/1.json
  def update
    @leito = Leito.find(params[:id])

    respond_to do |format|
      if @leito.update_attributes(params[:leito])
        format.html { redirect_to @leito, notice: 'Leito was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @leito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leitos/1
  # DELETE /leitos/1.json
  def destroy
    @leito = Leito.find(params[:id])
    @leito.destroy

    respond_to do |format|
      format.html { redirect_to leitos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/leitos_helper.rb
module LeitosHelper
end

app/views/leitos/_form.html.erb
<%= form_for(@leito) do |f| %>
  <% if @leito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leito.errors.count, "error") %> prohibited this leito from being saved:</h2>

      <ul>
      <% @leito.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cl %><br />
    <%= f.number_field :cl %>
  </div>
  <div class="field">
    <%= f.label :cir %><br />
    <%= f.number_field :cir %>
  </div>
  <div class="field">
    <%= f.label :obs %><br />
    <%= f.number_field :obs %>
  </div>
  <div class="field">
    <%= f.label :ped %><br />
    <%= f.number_field :ped %>
  </div>
  <div class="field">
    <%= f.label :uti %><br />
    <%= f.number_field :uti %>
  </div>
  <div class="field">
    <%= f.label :uti_neo %><br />
    <%= f.number_field :uti_neo %>
  </div>
  <div class="field">
    <%= f.label :isol %><br />
    <%= f.number_field :isol %>
  </div>
  <div class="field">
    <% if @leito.hospital %>
      <%= f.hidden_field 'hospital_id' %>
    <% else %>
      <%= f.label :hospital %><br />
      <%= f.collection_select(:hospital_id, Hospital.all, :id, :nome, :prompt => true) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leitos/edit.html.erb
<h1>Editing leito</h1>

<%= render 'form' %>

<%= link_to 'Show', @leito %> |
<%= link_to 'Back', leitos_path %>

app/views/leitos/index.html.erb
<h1>Listing leitos</h1>

<table>
  <tr>
    <th>Cl</th>
    <th>Cir</th>
    <th>Obs</th>
    <th>Ped</th>
    <th>Uti</th>
    <th>Uti neo</th>
    <th>Isol</th>
    <th>Hospital</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leitos.each do |leito| %>
  <tr>
    <td><%= leito.cl %></td>
    <td><%= leito.cir %></td>
    <td><%= leito.obs %></td>
    <td><%= leito.ped %></td>
    <td><%= leito.uti %></td>
    <td><%= leito.uti_neo %></td>
    <td><%= leito.isol %></td>
    <td><%= leito.hospital.nome %></td>
    <td><%= link_to 'Show', leito %></td>
    <td><%= link_to 'Edit', edit_leito_path(leito) %></td>
    <td><%= link_to 'Destroy', leito, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leito', new_leito_path %>

app/views/leitos/new.html.erb
<h1>New leito</h1>

<%= render 'form' %>

<%= link_to 'Back', leitos_path %>

app/views/leitos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cl:</b>
  <%= @leito.cl %>
</p>

<p>
  <b>Cir:</b>
  <%= @leito.cir %>
</p>

<p>
  <b>Obs:</b>
  <%= @leito.obs %>
</p>

<p>
  <b>Ped:</b>
  <%= @leito.ped %>
</p>

<p>
  <b>Uti:</b>
  <%= @leito.uti %>
</p>

<p>
  <b>Uti neo:</b>
  <%= @leito.uti_neo %>
</p>

<p>
  <b>Isol:</b>
  <%= @leito.isol %>
</p>

<p>
  <b>Hospital:</b>
  <%= @leito.hospital.nome %>
</p>

<% total = @leito.cl + @leito.cir + @leito.obs + @leito.ped + @leito.uti + @leito.uti_neo + @leito.isol %>

<p>
  <b>Tota de Leitos:</b>
  <%= total %>
</p>

<%= link_to 'Edit', edit_leito_path(@leito) %> |
<%= link_to 'Back', leitos_path %>