config/routes.rb
First::Application.routes.draw do
  resources :leitos

  resources :hospitais

  resources :municipios

  resources :gerencias

  resources :macros

end

app/models/macro.rb
class Macro < ActiveRecord::Base
	has_many :municipios
end

app/controllers/macros_controller.rb
class MacrosController < ApplicationController
  # GET /macros
  # GET /macros.json
  def index
    @macros = Macro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @macros }
    end
  end

  # GET /macros/1
  # GET /macros/1.json
  def show
    @macro = Macro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @macro }
    end
  end

  # GET /macros/new
  # GET /macros/new.json
  def new
    @macro = Macro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @macro }
    end
  end

  # GET /macros/1/edit
  def edit
    @macro = Macro.find(params[:id])
  end

  # POST /macros
  # POST /macros.json
  def create
    @macro = Macro.new(params[:macro])

    respond_to do |format|
      if @macro.save
        format.html { redirect_to @macro, notice: 'Macro was successfully created.' }
        format.json { render json: @macro, status: :created, location: @macro }
      else
        format.html { render action: "new" }
        format.json { render json: @macro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /macros/1
  # PUT /macros/1.json
  def update
    @macro = Macro.find(params[:id])

    respond_to do |format|
      if @macro.update_attributes(params[:macro])
        format.html { redirect_to @macro, notice: 'Macro was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @macro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /macros/1
  # DELETE /macros/1.json
  def destroy
    @macro = Macro.find(params[:id])
    @macro.destroy

    respond_to do |format|
      format.html { redirect_to macros_url }
      format.json { head :ok }
    end
  end
end

app/helpers/macros_helper.rb
module MacrosHelper
end

app/views/macros/_form.html.erb
<%= form_for(@macro) do |f| %>
  <% if @macro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@macro.errors.count, "error") %> prohibited this macro from being saved:</h2>

      <ul>
      <% @macro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/macros/edit.html.erb
<h1>Editing macro</h1>

<%= render 'form' %>

<%= link_to 'Show', @macro %> |
<%= link_to 'Back', macros_path %>

app/views/macros/index.html.erb
<h1>Listing macros</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @macros.each do |macro| %>
  <tr>
    <td><%= macro.codigo %></td>
    <td><%= link_to 'Show', macro %></td>
    <td><%= link_to 'Edit', edit_macro_path(macro) %></td>
    <td><%= link_to 'Destroy', macro, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Macro', new_macro_path %>

app/views/macros/new.html.erb
<h1>New macro</h1>

<%= render 'form' %>

<%= link_to 'Back', macros_path %>

app/views/macros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @macro.codigo %>
</p>


<%= link_to 'Edit', edit_macro_path(@macro) %> |
<%= link_to 'Back', macros_path %>