config/routes.rb
First::Application.routes.draw do
  resources :leitos

  resources :hospitais

  resources :municipios

  resources :gerencias

  resources :macros

end

app/models/gerencia.rb
class Gerencia < ActiveRecord::Base
	has_many :municipios
end

app/controllers/gerencias_controller.rb
class GerenciasController < ApplicationController
  # GET /gerencias
  # GET /gerencias.json
  def index
    @gerencias = Gerencia.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gerencias }
    end
  end

  # GET /gerencias/1
  # GET /gerencias/1.json
  def show
    @gerencia = Gerencia.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gerencia }
    end
  end

  # GET /gerencias/new
  # GET /gerencias/new.json
  def new
    @gerencia = Gerencia.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gerencia }
    end
  end

  # GET /gerencias/1/edit
  def edit
    @gerencia = Gerencia.find(params[:id])
  end

  # POST /gerencias
  # POST /gerencias.json
  def create
    @gerencia = Gerencia.new(params[:gerencia])

    respond_to do |format|
      if @gerencia.save
        format.html { redirect_to @gerencia, notice: 'Gerencia was successfully created.' }
        format.json { render json: @gerencia, status: :created, location: @gerencia }
      else
        format.html { render action: "new" }
        format.json { render json: @gerencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gerencias/1
  # PUT /gerencias/1.json
  def update
    @gerencia = Gerencia.find(params[:id])

    respond_to do |format|
      if @gerencia.update_attributes(params[:gerencia])
        format.html { redirect_to @gerencia, notice: 'Gerencia was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @gerencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gerencias/1
  # DELETE /gerencias/1.json
  def destroy
    @gerencia = Gerencia.find(params[:id])
    @gerencia.destroy

    respond_to do |format|
      format.html { redirect_to gerencias_url }
      format.json { head :ok }
    end
  end
end

app/helpers/gerencias_helper.rb
module GerenciasHelper
end

app/views/gerencias/_form.html.erb
<%= form_for(@gerencia) do |f| %>
  <% if @gerencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gerencia.errors.count, "error") %> prohibited this gerencia from being saved:</h2>

      <ul>
      <% @gerencia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gerencias/edit.html.erb
<h1>Editing gerencia</h1>

<%= render 'form' %>

<%= link_to 'Show', @gerencia %> |
<%= link_to 'Back', gerencias_path %>

app/views/gerencias/index.html.erb
<h1>Listing gerencias</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gerencias.each do |gerencia| %>
  <tr>
    <td><%= gerencia.codigo %></td>
    <td><%= link_to 'Show', gerencia %></td>
    <td><%= link_to 'Edit', edit_gerencia_path(gerencia) %></td>
    <td><%= link_to 'Destroy', gerencia, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gerencia', new_gerencia_path %>

app/views/gerencias/new.html.erb
<h1>New gerencia</h1>

<%= render 'form' %>

<%= link_to 'Back', gerencias_path %>

app/views/gerencias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @gerencia.codigo %>
</p>


<%= link_to 'Edit', edit_gerencia_path(@gerencia) %> |
<%= link_to 'Back', gerencias_path %>